id: A10F40F6F
title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast Expanse
type: translation
pechas:
- I218E206F
- I96CD58E8
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:44:10.007807
  last_modified_at: 2023-01-04 12:44:10.007827
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I218E206F/5D48: 333C
  I96CD58E8/2BFB: 333C
